work

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -10,7 +10,7 @@ PROTECTED_BRANCHES="^nathan/protect_push_to_main"
 
 if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
 then
-  echo ">> ERROR: Oops! You tried pushing directly to $BRANCH. Please create your own branch with \n \n >> git checkout -b <branch_name> \n \nand create a pull request.\n" && exit 1
+  echo ">> ERROR: Oops! You tried pushing directly to $BRANCH. Please create your own branch with \n \n>> git checkout -b <branch_name> \n \n>> and create a pull request.\n" && exit 1
 fi
 
 echo ">> Branch name checked. Good to go! \n ==="
